"""create initial fact knowledge layer tables

Revision ID: fc0833941cdf
Revises: 
Create Date: 2026-09-07 14:39:12.256167
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc0833941cdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_table('fact_types',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_types_name'), 'fact_types', ['name'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_index')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_id', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('fact_type_id', sa.String(length=100), nullable=False),
    sa.Column('attribute', sa.String(length=300), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('temporal_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fact_type_id'], ['fact_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_attribute'), 'facts', ['attribute'], unique=False)
    op.create_index(op.f('ix_facts_chunk_id'), 'facts', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_facts_document_id'), 'facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_facts_entity_id'), 'facts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_facts_fact_type_id'), 'facts', ['fact_type_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('source_fact_id', sa.String(length=100), nullable=False),
    sa.Column('target_fact_id', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_fact_id'), 'relationships', ['source_fact_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_fact_id'), 'relationships', ['target_fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_fact_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_fact_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_facts_fact_type_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_entity_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_document_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_chunk_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_attribute'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_fact_types_name'), table_name='fact_types')
    op.drop_table('fact_types')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('documents')
    # ### end Alembic commands ###
